name: gsettings-desktop-schemas
version: "48.0"
release: "1.el10"
source:
  type: srpm
  url: https://kojipkgs.fedoraproject.org/packages/gsettings-desktop-schemas/48.0/1.el10/src/gsettings-desktop-schemas-48.0-1.el10.src.rpm
arches:
  - x86_64
  - x86_64_v2
  - aarch64
el_version: 10
