name: gnome-shell
version: "48.0"
release: "1"
source:
  type: srpm
  url: https://kojipkgs.fedoraproject.org/packages/gnome-shell/48.0/1.fc42/src/gnome-shell-48.0-1.fc42.src.rpm
arches:
  - x86_64
  - x86_64_v2
  - aarch64
el_version: 10
description: "GNOME Shell desktop environment"
upstream: "https://gitlab.gnome.org/GNOME/gnome-shell"
