name: gnome-shell
version: "48.3"
release: "7.el10"
source:
  type: copr
  copr: jreilly1821/c10s-gnome
spec_source:
  type: local
  repo: https://src.fedoraproject.org/forks/jreilly1821/rpms/gnome-shell.git
  branch: rawhide-el10+-no-x11
arches:
  - x86_64
  - x86_64_v2
  - aarch64
el_version: 10
